cart_add_article:
    path:     /add/{id}
    defaults: { _controller: "sil13VitrineBundle:Order:addToCart"}
    methods:  POST
    requirements:
        id: \d

cart_remove_article:
    path:     /remove/{id}
    defaults: { _controller: "sil13VitrineBundle:Order:removeFromCart"}
    methods:  POST
    requirements:
        id: \d

