sil13\VitrineBundle\Entity\BuyOrder:
    type: entity
    table: null
    repositoryClass: sil13\VitrineBundle\Repository\BuyOrderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        count:
          type: integer
          length: 5
    manyToOne:
        user:
            inversedBy: order
            targetEntity: sil13\VitrineBundle\Entity\User
        article:
            inversedBy: order
            targetEntity: sil13\VitrineBundle\Entity\Article
    lifecycleCallbacks: {  }
