sil13\VitrineBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: sil13\VitrineBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '30'
    lifecycleCallbacks: {  }
