sil13\VitrineBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        order:
            mappedBy: users
            targetEntity: sil13\VitrineBundle\Entity\BuyOrder
